# API-2 Módulo 2 Procesamiento de Datos

In [1]:
# importamos las bibliotecas pandas y numpy
import pandas as pd 
import numpy as np

## Creación de array usando numpy

In [2]:
# diseño de array 3D
array_3d=np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

print("\nImpresion array 3D\n")
print(array_3d,"\n")


Impresion array 3D

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 



## Como ubicar un dato específico en un array 3D

In [6]:
# muestro dato del array
print("\nMostrar dato del array 3D\n")
print("Selecciono primer índice 1, primer bloque\n")
print("Selecciono segundo índice 1, dentro del primer bloque, elijo segunda fila\n")
print("Selecciono tercer índice 2, dentro de esa fila elijo la tercer columna\n")
print("Resultado de la busqueda: ", array_3d[1,1,2])


Mostrar dato del array 3D

Selecciono primer índice 1, primer bloque

Selecciono segundo índice 1, dentro del primer bloque, elijo segunda fila

Selecciono tercer índice 2, dentro de esa fila elijo la tercer columna

Resultado de la busqueda:  15


## Usando la funcion - append - agregamos datos al array

In [ ]:
# convierto la nueva fila a shape (1, 3)

columnas_nuevas=np.array([
    [[100], [200], [300]],
    [[400], [500], [600]],
    [[700], [800], [900]]
])

# uso append con axis=1 para agregar filas
nuevo_array=np.append(array_3d,columnas_nuevas, axis=2)

print("\nAgredo datos \n")
print(nuevo_array)


Agredo datos 

[[[  1   2   3 100]
  [  4   5   6 200]
  [  7   8   9 300]]

 [[ 10  11  12 400]
  [ 13  14  15 500]
  [ 16  17  18 600]]

 [[ 19  20  21 700]
  [ 22  23  24 800]
  [ 25  26  27 900]]]


## Creo un array 3D de dimensiones (3,3)

In [24]:
array=np.array([
    [100,110,120],
    [400,410,420],
    [700,710,720]
])

print("\nInforme de la dimensión del array:\n")
print(array.shape)


Informe de la dimensión del array:

(3, 3)


## Usando pandas creo dos series distintas unas de marcas_productos y otra color_cantidad

In [26]:
# creo serie marca_productos
productos=pd.Series(["Motorola","Samsung","Philco","Dream"], index=range(4))
print("\nMuestra Serie marca_producto\n")
print(productos)


Muestra Serie marca_producto

0    Motorola
1     Samsung
2      Philco
3       Dream
dtype: object


In [27]:
# creo la serie color_cantidad con el nombre de color en la columna de indice
color=pd.Series([10,5,34,67,59], index=['Azul','Blanco','Celeste','Negro','Rojo'])
print("\nMuestra Serie color_cantidad\n")
print(color)


Muestra Serie color_cantidad

Azul       10
Blanco      5
Celeste    34
Negro      67
Rojo       59
dtype: int64
