# API-2 Módulo 2 Procesamiento de Datos

In [2]:
# importamos las bibliotecas pandas y numpy
import pandas as pd 
import numpy as np

## Creación de array usando numpy

In [ ]:
# diseño de array 3D usando la función random de numpy
array3d=np.random.randint(1,100,size=(2,1,3))

print("\nImpresion array 3D\n")
print(array3d,"\n")


Impresion array 3D

[[[75 61 71]]

 [[83 35 31]]] 



## Como ubicar un dato específico en un array 3D

In [8]:
# muestro dato del array
print("\nMostrar dato del array 3D\n")
print("Selecciono primer índice 1, primer bloque\n")
print("Selecciono segundo índice 1, dentro del primer bloque, elijo segunda fila\n")
print("Selecciono tercer índice 2, segunda capa\n")
print("Resultado de la busqueda: ", array3d[1,0,2])


Mostrar dato del array 3D

Selecciono primer índice 1, primer bloque

Selecciono segundo índice 1, dentro del primer bloque, elijo segunda fila

Selecciono tercer índice 2, segunda capa

Resultado de la busqueda:  31


## Usando la funcion - append - agregamos datos al array

In [ ]:
# convierto la nueva fila a shape (1, 3)
columnas_nuevas=np.array([[[100,200,300]]]).reshape(1,1,3)

# uso append con axis=1 para agregar filas
array3d=np.append(array3d,columnas_nuevas, axis=0)

print("\nAgredo datos \n")
print(array3d)


Agredo datos 

[[[ 75  61  71]]

 [[ 83  35  31]]

 [[100 200 300]]]


## Convertir un array 3D en uno de 2D para tener un shape (3,3)

In [10]:
# convierto el array 3d a uno de 2d para que el shape sea (3,3)
array2d=array3d.reshape(3,3)
    
print("\nInforme de la dimensión del array 2D:\n")
print(array2d,"\n")
print(array2d.shape)


Informe de la dimensión del array 2D:

[[ 75  61  71]
 [ 83  35  31]
 [100 200 300]] 

(3, 3)


## Usando pandas creo dos series distintas unas de marcas_productos y otra color_cantidad

In [26]:
# creo serie marca_productos
productos=pd.Series(["Motorola","Samsung","Philco","Dream"], index=range(4))
print("\nMuestra Serie marca_producto\n")
print(productos)


Muestra Serie marca_producto

0    Motorola
1     Samsung
2      Philco
3       Dream
dtype: object


In [27]:
# creo la serie color_cantidad con el nombre de color en la columna de indice
color=pd.Series([10,5,34,67,59], index=['Azul','Blanco','Celeste','Negro','Rojo'])
print("\nMuestra Serie color_cantidad\n")
print(color)


Muestra Serie color_cantidad

Azul       10
Blanco      5
Celeste    34
Negro      67
Rojo       59
dtype: int64
